// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Env.flutterApiKeyForAndroid,
    appId: '1:283095395659:android:f30539aaef86b8b1804cce',
    messagingSenderId: '283095395659',
    projectId: 'ourtube-onboarding-by-milo',
    storageBucket: 'ourtube-onboarding-by-milo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.flutterApiKeyForIos,
    appId: '1:283095395659:ios:24dc7815a12eaae7804cce',
    messagingSenderId: '283095395659',
    projectId: 'ourtube-onboarding-by-milo',
    storageBucket: 'ourtube-onboarding-by-milo.appspot.com',
    iosClientId: '283095395659-v8qd8v2mfbde55t7eddchmd54vqq2v4i.apps.googleusercontent.com',
    iosBundleId: 'ourtube.co.kr.ourtubeOnboardingByMilo',
  );
}
